#parameter list
SUBMODS ?=
#parameter list

CLEANTARGET = clean
INSTALLTARGET = install
TAGSTARGET = tags
GCOVTARGET = gcov
GCOVCLEANTARGET = gcovclean

SUBMODSCLEAN = $(patsubst %, %.$(CLEANTARGET), $(SUBMODS)) 
SUBMODSINSTALL = $(patsubst %, %.$(INSTALLTARGET), $(SUBMODS)) 
SUBMODSTAGS = $(patsubst %, %.$(TAGSTARGET), $(SUBMODS))
SUBMODSGCOV = $(patsubst %, %.$(GCOVTARGET), $(SUBMODS))
SUBMODSGCOVCLEAN = $(patsubst %, %.$(GCOVCLEANTARGET), $(SUBMODS))

.PHONY: all $(CLEANTARGET) $(INSTALLTARGET) $(TAGSTARGET) $(GCOVTARGET) $(GCOVCLEANTARGET) $(SUBMODS)

all: $(SUBMODS)

$(CLEANTARGET): $(SUBMODSCLEAN)

$(INSTALLTARGET): $(SUBMODSINSTALL)

$(TAGSTARGET): $(SUBMODSTAGS)

$(GCOVTARGET): $(SUBMODSGCOV)

$(GCOVCLEANTARGET): $(SUBMODSGCOVCLEAN)

$(SUBMODS):
	cd $@ && $(MAKE);

$(SUBMODSGCOV): 
	cd $(patsubst %.$(GCOVTARGET),%, $@)  && $(MAKE) $(GCOVTARGET);

$(SUBMODSGCOVCLEAN): 
	cd $(patsubst %.$(GCOVCLEANTARGET),%, $@)  && $(MAKE) $(GCOVCLEANTARGET);

$(SUBMODSTAGS): 
	cd $(patsubst %.$(TAGSTARGET),%, $@)  && $(MAKE) $(TAGSTARGET);

$(SUBMODSCLEAN): 
	cd $(patsubst %.$(CLEANTARGET),%, $@)  && $(MAKE) $(CLEANTARGET);

$(SUBMODSINSTALL): 
	cd $(patsubst %.$(INSTALLTARGET),%, $@)  && $(MAKE) $(INSTALLTARGET);

