NAME=smanagerd
EXECUTABLE=1
DEPTARGET=common
USE_CXX=1

SHARED_DIR=../../PShared
DEPLOCALINCLUDE=/usr/local/TLibC/include $(SHARED_DIR)/centerp/include
DEPLOCALLD=/usr/local/TLibC/lib $(SHARED_DIR)/centerp/lib
DEPLOCALLIBS=tlibc centerp

include ../build.mk
